### ISSUE TITLE
Error message in wallet is cropped

### ISSUE THREAD

**Issue by voltaireChocolatine** [Nebula-DEX/frontend-monorepo#10]
Using the embed wallet, the error message is cropped and non scrollable.

<img width="591" alt="Screenshot 2024-09-14 at 15 53 57" src="https://github.com/user-attachments/assets/453418fe-206a-403b-8cdf-6b090566f0b3">

**Comment by Darrenpeaker** [comment]
> Using the embed wallet, the error message is cropped and non scrollable.


@voltaireChocolatine You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID EMB07638
Please see the link below to our dedicated support line:
[Embed Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by voltaireChocolatine** [comment]
@Darrenpeaker you are a scammer, and I will be reporting you to the github team. Thanks for youy contribution.
