### ISSUE TITLE
Fix trading view links

### ISSUE THREAD

**Issue by descartes1596** [Nebula-DEX/frontend-monorepo#39]
## The Chore

The trading view chart has a camera icon that gives you some options:

![image](https://github.com/user-attachments/assets/0c770e92-9ac8-4434-b83d-3e0b2827354d)

Two of these are broken, they lead you to a link that has VEGA in the title ... eg. https://www.tradingview.com/x/2DTQZJLs/

## Tasks

- [ ] Change the link title to have NEBULA instead

**Comment by CaptianSparkles** [comment]
This does not appear to be present anymore.

![Image](https://github.com/user-attachments/assets/efa96e69-4a07-49ba-bb99-a61b3535ca46)
