### ISSUE TITLE
Mising border radius in couple of places

### ISSUE THREAD

**Issue by voltaireChocolatine** [Nebula-DEX/frontend-monorepo#8]
<img width="1165" alt="Screenshot 2024-09-14 at 15 50 28" src="https://github.com/user-attachments/assets/77ac7746-aeaa-41e1-8b81-d42c3859c835">
<img width="1376" alt="Screenshot 2024-09-14 at 15 51 08" src="https://github.com/user-attachments/assets/bd51c187-5cd6-48cf-9617-67a5dfb772bd">
<img width="1376" alt="Screenshot 2024-09-14 at 15 51 08" src="https://github.com/user-attachments/assets/844ce22f-0722-48bc-9222-a3b65891c5c8">
<img width="757" alt="Screenshot 2024-09-14 at 15 51 43" src="https://github.com/user-attachments/assets/b71a9686-6586-4fae-ab52-1463ec82a128">

**Comment by descartes1596** [comment]
This is now mostly done.  Remaining things are on #45
